version: 2

builds:
  - &build
    main: ./cmd/spectre-ingress
    binary: spectre-ingress
    id: spectre-ingress
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid= -X github.com/block/spectre/internal.Version={{ .Version }}
  - <<: *build
    main: ./cmd/spectre-egress
    binary: spectre-egress
    id: spectre-egress

archives:
  - formats: [tar.gz]
    # This name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
