// Code generated by spectre-gen proto. DO NOT EDIT.
// Source: service.proto

declare module "spectre.sample.v1" {
  export interface GetUserRequest {
    id: string;
  }

  export interface GetUserResponse {
    user?: import("spectre.sample.v1").User;
  }

  export interface ListUsersRequest {
    ids: string[];
    role?: import("spectre.sample.v1").Role;
  }

  export interface ListUsersResponse {
    users: import("spectre.sample.v1").User[];
    generatedAt?: string;
    totalCount: string;
  }

  export interface UserService {
    GetUser(request: import("spectre.sample.v1").GetUserRequest): import("spectre.sample.v1").GetUserResponse;
    ListUsers(request: import("spectre.sample.v1").ListUsersRequest): import("spectre.sample.v1").ListUsersResponse;
  }
}
