// Code generated by spectre-gen proto. DO NOT EDIT.
// Source: users.proto

declare module "spectre.sample.v1" {
  export type Role = "ROLE_UNSPECIFIED" | "ROLE_READER" | "ROLE_EDITOR" | "ROLE_ADMIN";

  export interface User {
    id: string;
    name: string;
    nickname?: string;
    roles: import("spectre.sample.v1").Role[];
    labels: Record<string, string>;
    profile?: import("spectre.sample.v1").User.Profile;
    avatar: string;
    revision: string;
    createdAt?: string;
    email?: string;
    phone?: import("spectre.sample.v1").Phone;
  }

  export namespace User {
    export interface Profile {
      addresses: import("spectre.sample.v1").Address[];
      marketingConsent?: boolean;
      preferences: Record<string, import("spectre.sample.v1").Preference>;
    }
  }

  export interface Address {
    lines: string[];
    city: string;
    postalCode: string;
    countryCode: string;
  }

  export interface Phone {
    countryCode: string;
    number: string;
    extension?: string;
  }

  export interface Preference {
    text?: string;
    enabled?: boolean;
    weight?: number | "-Infinity" | "Infinity" | "NaN";
  }
}
