// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: forecasts.proto

package samplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchForecastRequest binds the path wildcard, so egress can hash the request.
type FetchForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *string                `protobuf:"bytes,1,opt,name=location,proto3,oneof" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchForecastRequest) Reset() {
	*x = FetchForecastRequest{}
	mi := &file_forecasts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchForecastRequest) ProtoMessage() {}

func (x *FetchForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forecasts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchForecastRequest.ProtoReflect.Descriptor instead.
func (*FetchForecastRequest) Descriptor() ([]byte, []int) {
	return file_forecasts_proto_rawDescGZIP(), []int{0}
}

func (x *FetchForecastRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

// FetchForecastResponse holds a forecast or, when the request fails, an error.
type FetchForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecast      *Forecast              `protobuf:"bytes,1,opt,name=forecast,proto3" json:"forecast,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchForecastResponse) Reset() {
	*x = FetchForecastResponse{}
	mi := &file_forecasts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchForecastResponse) ProtoMessage() {}

func (x *FetchForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forecasts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchForecastResponse.ProtoReflect.Descriptor instead.
func (*FetchForecastResponse) Descriptor() ([]byte, []int) {
	return file_forecasts_proto_rawDescGZIP(), []int{1}
}

func (x *FetchForecastResponse) GetForecast() *Forecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *FetchForecastResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_forecasts_proto protoreflect.FileDescriptor

const file_forecasts_proto_rawDesc = "" +
	"\n" +
	"\x0fforecasts.proto\x12\x11spectre.sample.v1\x1a\rweather.proto\"D\n" +
	"\x14FetchForecastRequest\x12\x1f\n" +
	"\blocation\x18\x01 \x01(\tH\x00R\blocation\x88\x01\x01B\v\n" +
	"\t_location\"{\n" +
	"\x15FetchForecastResponse\x127\n" +
	"\bforecast\x18\x01 \x01(\v2\x1b.spectre.sample.v1.ForecastR\bforecast\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message2}\n" +
	"\x17ForecastProviderService\x12b\n" +
	"\rFetchForecast\x12'.spectre.sample.v1.FetchForecastRequest\x1a(.spectre.sample.v1.FetchForecastResponseB6Z4github.com/block/spectre/internal/sample/pb;samplepbb\x06proto3"

var (
	file_forecasts_proto_rawDescOnce sync.Once
	file_forecasts_proto_rawDescData []byte
)

func file_forecasts_proto_rawDescGZIP() []byte {
	file_forecasts_proto_rawDescOnce.Do(func() {
		file_forecasts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forecasts_proto_rawDesc), len(file_forecasts_proto_rawDesc)))
	})
	return file_forecasts_proto_rawDescData
}

var file_forecasts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forecasts_proto_goTypes = []any{
	(*FetchForecastRequest)(nil),  // 0: spectre.sample.v1.FetchForecastRequest
	(*FetchForecastResponse)(nil), // 1: spectre.sample.v1.FetchForecastResponse
	(*Forecast)(nil),              // 2: spectre.sample.v1.Forecast
}
var file_forecasts_proto_depIdxs = []int32{
	2, // 0: spectre.sample.v1.FetchForecastResponse.forecast:type_name -> spectre.sample.v1.Forecast
	0, // 1: spectre.sample.v1.ForecastProviderService.FetchForecast:input_type -> spectre.sample.v1.FetchForecastRequest
	1, // 2: spectre.sample.v1.ForecastProviderService.FetchForecast:output_type -> spectre.sample.v1.FetchForecastResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forecasts_proto_init() }
func file_forecasts_proto_init() {
	if File_forecasts_proto != nil {
		return
	}
	file_weather_proto_init()
	file_forecasts_proto_msgTypes[0].OneofWrappers = []any{}
	file_forecasts_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forecasts_proto_rawDesc), len(file_forecasts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forecasts_proto_goTypes,
		DependencyIndexes: file_forecasts_proto_depIdxs,
		MessageInfos:      file_forecasts_proto_msgTypes,
	}.Build()
	File_forecasts_proto = out.File
	file_forecasts_proto_goTypes = nil
	file_forecasts_proto_depIdxs = nil
}
