// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: users.proto

package samplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_READER      Role = 1
	Role_ROLE_EDITOR      Role = 2
	Role_ROLE_ADMIN       Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_READER",
		2: "ROLE_EDITOR",
		3: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_READER":      1,
		"ROLE_EDITOR":      2,
		"ROLE_ADMIN":       3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_users_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_users_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

// User exercises presence, nested collections, and values that need special JSON encoding.
type User struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname  *string                `protobuf:"bytes,3,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Roles     []Role                 `protobuf:"varint,4,rep,packed,name=roles,proto3,enum=spectre.sample.v1.Role" json:"roles,omitempty"`
	Labels    map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Profile   *User_Profile          `protobuf:"bytes,6,opt,name=profile,proto3" json:"profile,omitempty"`
	Avatar    []byte                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Revision  uint64                 `protobuf:"varint,8,opt,name=revision,proto3" json:"revision,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Types that are valid to be assigned to Contact:
	//
	//	*User_Email
	//	*User_Phone
	Contact       isUser_Contact `protobuf_oneof:"contact"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *User) GetRoles() []Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *User) GetProfile() *User_Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *User) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetContact() isUser_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		if x, ok := x.Contact.(*User_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *User) GetPhone() *Phone {
	if x != nil {
		if x, ok := x.Contact.(*User_Phone); ok {
			return x.Phone
		}
	}
	return nil
}

type isUser_Contact interface {
	isUser_Contact()
}

type User_Email struct {
	Email string `protobuf:"bytes,10,opt,name=email,proto3,oneof"`
}

type User_Phone struct {
	Phone *Phone `protobuf:"bytes,11,opt,name=phone,proto3,oneof"`
}

func (*User_Email) isUser_Contact() {}

func (*User_Phone) isUser_Contact() {}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode    string                 `protobuf:"bytes,3,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type Phone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Extension     *string                `protobuf:"bytes,3,opt,name=extension,proto3,oneof" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Phone) Reset() {
	*x = Phone{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *Phone) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Phone) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Phone) GetExtension() string {
	if x != nil && x.Extension != nil {
		return *x.Extension
	}
	return ""
}

type Preference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Preference_Text
	//	*Preference_Enabled
	//	*Preference_Weight
	Value         isPreference_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preference) Reset() {
	*x = Preference{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preference) ProtoMessage() {}

func (x *Preference) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preference.ProtoReflect.Descriptor instead.
func (*Preference) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *Preference) GetValue() isPreference_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Preference) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*Preference_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Preference) GetEnabled() bool {
	if x != nil {
		if x, ok := x.Value.(*Preference_Enabled); ok {
			return x.Enabled
		}
	}
	return false
}

func (x *Preference) GetWeight() float64 {
	if x != nil {
		if x, ok := x.Value.(*Preference_Weight); ok {
			return x.Weight
		}
	}
	return 0
}

type isPreference_Value interface {
	isPreference_Value()
}

type Preference_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Preference_Enabled struct {
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3,oneof"`
}

type Preference_Weight struct {
	Weight float64 `protobuf:"fixed64,3,opt,name=weight,proto3,oneof"`
}

func (*Preference_Text) isPreference_Value() {}

func (*Preference_Enabled) isPreference_Value() {}

func (*Preference_Weight) isPreference_Value() {}

type User_Profile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Addresses        []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	MarketingConsent *bool                  `protobuf:"varint,2,opt,name=marketing_consent,json=marketingConsent,proto3,oneof" json:"marketing_consent,omitempty"`
	Preferences      map[string]*Preference `protobuf:"bytes,3,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User_Profile) Reset() {
	*x = User_Profile{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Profile) ProtoMessage() {}

func (x *User_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Profile.ProtoReflect.Descriptor instead.
func (*User_Profile) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0, 1}
}

func (x *User_Profile) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *User_Profile) GetMarketingConsent() bool {
	if x != nil && x.MarketingConsent != nil {
		return *x.MarketingConsent
	}
	return false
}

func (x *User_Profile) GetPreferences() map[string]*Preference {
	if x != nil {
		return x.Preferences
	}
	return nil
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x11spectre.sample.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x06\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\bnickname\x18\x03 \x01(\tH\x01R\bnickname\x88\x01\x01\x12-\n" +
	"\x05roles\x18\x04 \x03(\x0e2\x17.spectre.sample.v1.RoleR\x05roles\x12;\n" +
	"\x06labels\x18\x05 \x03(\v2#.spectre.sample.v1.User.LabelsEntryR\x06labels\x129\n" +
	"\aprofile\x18\x06 \x01(\v2\x1f.spectre.sample.v1.User.ProfileR\aprofile\x12\x16\n" +
	"\x06avatar\x18\a \x01(\fR\x06avatar\x12\x1a\n" +
	"\brevision\x18\b \x01(\x04R\brevision\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x05email\x18\n" +
	" \x01(\tH\x00R\x05email\x120\n" +
	"\x05phone\x18\v \x01(\v2\x18.spectre.sample.v1.PhoneH\x00R\x05phone\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\xbe\x02\n" +
	"\aProfile\x128\n" +
	"\taddresses\x18\x01 \x03(\v2\x1a.spectre.sample.v1.AddressR\taddresses\x120\n" +
	"\x11marketing_consent\x18\x02 \x01(\bH\x00R\x10marketingConsent\x88\x01\x01\x12R\n" +
	"\vpreferences\x18\x03 \x03(\v20.spectre.sample.v1.User.Profile.PreferencesEntryR\vpreferences\x1a]\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.spectre.sample.v1.PreferenceR\x05value:\x028\x01B\x14\n" +
	"\x12_marketing_consentB\t\n" +
	"\acontactB\v\n" +
	"\t_nickname\"w\n" +
	"\aAddress\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1f\n" +
	"\vpostal_code\x18\x03 \x01(\tR\n" +
	"postalCode\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\"s\n" +
	"\x05Phone\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12!\n" +
	"\textension\x18\x03 \x01(\tH\x00R\textension\x88\x01\x01B\f\n" +
	"\n" +
	"_extension\"a\n" +
	"\n" +
	"Preference\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x1a\n" +
	"\aenabled\x18\x02 \x01(\bH\x00R\aenabled\x12\x18\n" +
	"\x06weight\x18\x03 \x01(\x01H\x00R\x06weightB\a\n" +
	"\x05value*N\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_READER\x10\x01\x12\x0f\n" +
	"\vROLE_EDITOR\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x03B6Z4github.com/block/spectre/internal/sample/pb;samplepbb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_users_proto_goTypes = []any{
	(Role)(0),                     // 0: spectre.sample.v1.Role
	(*User)(nil),                  // 1: spectre.sample.v1.User
	(*Address)(nil),               // 2: spectre.sample.v1.Address
	(*Phone)(nil),                 // 3: spectre.sample.v1.Phone
	(*Preference)(nil),            // 4: spectre.sample.v1.Preference
	nil,                           // 5: spectre.sample.v1.User.LabelsEntry
	(*User_Profile)(nil),          // 6: spectre.sample.v1.User.Profile
	nil,                           // 7: spectre.sample.v1.User.Profile.PreferencesEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_users_proto_depIdxs = []int32{
	0, // 0: spectre.sample.v1.User.roles:type_name -> spectre.sample.v1.Role
	5, // 1: spectre.sample.v1.User.labels:type_name -> spectre.sample.v1.User.LabelsEntry
	6, // 2: spectre.sample.v1.User.profile:type_name -> spectre.sample.v1.User.Profile
	8, // 3: spectre.sample.v1.User.created_at:type_name -> google.protobuf.Timestamp
	3, // 4: spectre.sample.v1.User.phone:type_name -> spectre.sample.v1.Phone
	2, // 5: spectre.sample.v1.User.Profile.addresses:type_name -> spectre.sample.v1.Address
	7, // 6: spectre.sample.v1.User.Profile.preferences:type_name -> spectre.sample.v1.User.Profile.PreferencesEntry
	4, // 7: spectre.sample.v1.User.Profile.PreferencesEntry.value:type_name -> spectre.sample.v1.Preference
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	file_users_proto_msgTypes[0].OneofWrappers = []any{
		(*User_Email)(nil),
		(*User_Phone)(nil),
	}
	file_users_proto_msgTypes[2].OneofWrappers = []any{}
	file_users_proto_msgTypes[3].OneofWrappers = []any{
		(*Preference_Text)(nil),
		(*Preference_Enabled)(nil),
		(*Preference_Weight)(nil),
	}
	file_users_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		EnumInfos:         file_users_proto_enumTypes,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
