// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: weather.proto

package samplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetForecastRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// GetForecastResponse holds a forecast or, when the request fails, an error.
type GetForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecast      *Forecast              `protobuf:"bytes,1,opt,name=forecast,proto3" json:"forecast,omitempty"`
	Success       *bool                  `protobuf:"varint,2,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastResponse) Reset() {
	*x = GetForecastResponse{}
	mi := &file_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastResponse) ProtoMessage() {}

func (x *GetForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastResponse.ProtoReflect.Descriptor instead.
func (*GetForecastResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetForecastResponse) GetForecast() *Forecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *GetForecastResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *GetForecastResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetForecastV2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastV2Request) Reset() {
	*x = GetForecastV2Request{}
	mi := &file_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastV2Request) ProtoMessage() {}

func (x *GetForecastV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastV2Request.ProtoReflect.Descriptor instead.
func (*GetForecastV2Request) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{2}
}

func (x *GetForecastV2Request) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// GetForecastV2Response adds the location's active alerts, in no particular order.
type GetForecastV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecast      *Forecast              `protobuf:"bytes,1,opt,name=forecast,proto3" json:"forecast,omitempty"`
	Alerts        []*Alert               `protobuf:"bytes,2,rep,name=alerts,proto3" json:"alerts,omitempty"`
	Success       *bool                  `protobuf:"varint,3,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastV2Response) Reset() {
	*x = GetForecastV2Response{}
	mi := &file_weather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastV2Response) ProtoMessage() {}

func (x *GetForecastV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastV2Response.ProtoReflect.Descriptor instead.
func (*GetForecastV2Response) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{3}
}

func (x *GetForecastV2Response) GetForecast() *Forecast {
	if x != nil {
		return x.Forecast
	}
	return nil
}

func (x *GetForecastV2Response) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *GetForecastV2Response) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *GetForecastV2Response) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_weather_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{4}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_weather_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GetStatusResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type Forecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Days          []*DailyForecast       `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	mi := &file_weather_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{6}
}

func (x *Forecast) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Forecast) GetDays() []*DailyForecast {
	if x != nil {
		return x.Days
	}
	return nil
}

type DailyForecast struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Date                 string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	High                 *Temperature           `protobuf:"bytes,2,opt,name=high,proto3" json:"high,omitempty"`
	Low                  *Temperature           `protobuf:"bytes,3,opt,name=low,proto3" json:"low,omitempty"`
	PrecipitationPercent int32                  `protobuf:"varint,4,opt,name=precipitation_percent,json=precipitationPercent,proto3" json:"precipitation_percent,omitempty"`
	Wind                 *Wind                  `protobuf:"bytes,5,opt,name=wind,proto3" json:"wind,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DailyForecast) Reset() {
	*x = DailyForecast{}
	mi := &file_weather_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyForecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyForecast) ProtoMessage() {}

func (x *DailyForecast) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyForecast.ProtoReflect.Descriptor instead.
func (*DailyForecast) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{7}
}

func (x *DailyForecast) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyForecast) GetHigh() *Temperature {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *DailyForecast) GetLow() *Temperature {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *DailyForecast) GetPrecipitationPercent() int32 {
	if x != nil {
		return x.PrecipitationPercent
	}
	return 0
}

func (x *DailyForecast) GetWind() *Wind {
	if x != nil {
		return x.Wind
	}
	return nil
}

type Temperature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Degrees       float64                `protobuf:"fixed64,1,opt,name=degrees,proto3" json:"degrees,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	mi := &file_weather_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{8}
}

func (x *Temperature) GetDegrees() float64 {
	if x != nil {
		return x.Degrees
	}
	return 0
}

func (x *Temperature) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type Wind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpeedKph      float64                `protobuf:"fixed64,1,opt,name=speed_kph,json=speedKph,proto3" json:"speed_kph,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wind) Reset() {
	*x = Wind{}
	mi := &file_weather_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wind) ProtoMessage() {}

func (x *Wind) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wind.ProtoReflect.Descriptor instead.
func (*Wind) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{9}
}

func (x *Wind) GetSpeedKph() float64 {
	if x != nil {
		return x.SpeedKph
	}
	return 0
}

func (x *Wind) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Headline      string                 `protobuf:"bytes,3,opt,name=headline,proto3" json:"headline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_weather_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{10}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

var File_weather_proto protoreflect.FileDescriptor

const file_weather_proto_rawDesc = "" +
	"\n" +
	"\rweather.proto\x12\x11spectre.sample.v1\"0\n" +
	"\x12GetForecastRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"\xa4\x01\n" +
	"\x13GetForecastResponse\x127\n" +
	"\bforecast\x18\x01 \x01(\v2\x1b.spectre.sample.v1.ForecastR\bforecast\x12\x1d\n" +
	"\asuccess\x18\x02 \x01(\bH\x00R\asuccess\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x01R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_successB\n" +
	"\n" +
	"\b_message\"2\n" +
	"\x14GetForecastV2Request\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"\xd8\x01\n" +
	"\x15GetForecastV2Response\x127\n" +
	"\bforecast\x18\x01 \x01(\v2\x1b.spectre.sample.v1.ForecastR\bforecast\x120\n" +
	"\x06alerts\x18\x02 \x03(\v2\x18.spectre.sample.v1.AlertR\x06alerts\x12\x1d\n" +
	"\asuccess\x18\x03 \x01(\bH\x00R\asuccess\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x01R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_successB\n" +
	"\n" +
	"\b_message\"\x12\n" +
	"\x10GetStatusRequest\"r\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\\\n" +
	"\bForecast\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x124\n" +
	"\x04days\x18\x02 \x03(\v2 .spectre.sample.v1.DailyForecastR\x04days\"\xeb\x01\n" +
	"\rDailyForecast\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x122\n" +
	"\x04high\x18\x02 \x01(\v2\x1e.spectre.sample.v1.TemperatureR\x04high\x120\n" +
	"\x03low\x18\x03 \x01(\v2\x1e.spectre.sample.v1.TemperatureR\x03low\x123\n" +
	"\x15precipitation_percent\x18\x04 \x01(\x05R\x14precipitationPercent\x12+\n" +
	"\x04wind\x18\x05 \x01(\v2\x17.spectre.sample.v1.WindR\x04wind\";\n" +
	"\vTemperature\x12\x18\n" +
	"\adegrees\x18\x01 \x01(\x01R\adegrees\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\"A\n" +
	"\x04Wind\x12\x1b\n" +
	"\tspeed_kph\x18\x01 \x01(\x01R\bspeedKph\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\"O\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x1a\n" +
	"\bheadline\x18\x03 \x01(\tR\bheadline2\xaa\x02\n" +
	"\x0eWeatherService\x12\\\n" +
	"\vGetForecast\x12%.spectre.sample.v1.GetForecastRequest\x1a&.spectre.sample.v1.GetForecastResponse\x12b\n" +
	"\rGetForecastV2\x12'.spectre.sample.v1.GetForecastV2Request\x1a(.spectre.sample.v1.GetForecastV2Response\x12V\n" +
	"\tGetStatus\x12#.spectre.sample.v1.GetStatusRequest\x1a$.spectre.sample.v1.GetStatusResponseB6Z4github.com/block/spectre/internal/sample/pb;samplepbb\x06proto3"

var (
	file_weather_proto_rawDescOnce sync.Once
	file_weather_proto_rawDescData []byte
)

func file_weather_proto_rawDescGZIP() []byte {
	file_weather_proto_rawDescOnce.Do(func() {
		file_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)))
	})
	return file_weather_proto_rawDescData
}

var file_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_weather_proto_goTypes = []any{
	(*GetForecastRequest)(nil),    // 0: spectre.sample.v1.GetForecastRequest
	(*GetForecastResponse)(nil),   // 1: spectre.sample.v1.GetForecastResponse
	(*GetForecastV2Request)(nil),  // 2: spectre.sample.v1.GetForecastV2Request
	(*GetForecastV2Response)(nil), // 3: spectre.sample.v1.GetForecastV2Response
	(*GetStatusRequest)(nil),      // 4: spectre.sample.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 5: spectre.sample.v1.GetStatusResponse
	(*Forecast)(nil),              // 6: spectre.sample.v1.Forecast
	(*DailyForecast)(nil),         // 7: spectre.sample.v1.DailyForecast
	(*Temperature)(nil),           // 8: spectre.sample.v1.Temperature
	(*Wind)(nil),                  // 9: spectre.sample.v1.Wind
	(*Alert)(nil),                 // 10: spectre.sample.v1.Alert
}
var file_weather_proto_depIdxs = []int32{
	6,  // 0: spectre.sample.v1.GetForecastResponse.forecast:type_name -> spectre.sample.v1.Forecast
	6,  // 1: spectre.sample.v1.GetForecastV2Response.forecast:type_name -> spectre.sample.v1.Forecast
	10, // 2: spectre.sample.v1.GetForecastV2Response.alerts:type_name -> spectre.sample.v1.Alert
	7,  // 3: spectre.sample.v1.Forecast.days:type_name -> spectre.sample.v1.DailyForecast
	8,  // 4: spectre.sample.v1.DailyForecast.high:type_name -> spectre.sample.v1.Temperature
	8,  // 5: spectre.sample.v1.DailyForecast.low:type_name -> spectre.sample.v1.Temperature
	9,  // 6: spectre.sample.v1.DailyForecast.wind:type_name -> spectre.sample.v1.Wind
	0,  // 7: spectre.sample.v1.WeatherService.GetForecast:input_type -> spectre.sample.v1.GetForecastRequest
	2,  // 8: spectre.sample.v1.WeatherService.GetForecastV2:input_type -> spectre.sample.v1.GetForecastV2Request
	4,  // 9: spectre.sample.v1.WeatherService.GetStatus:input_type -> spectre.sample.v1.GetStatusRequest
	1,  // 10: spectre.sample.v1.WeatherService.GetForecast:output_type -> spectre.sample.v1.GetForecastResponse
	3,  // 11: spectre.sample.v1.WeatherService.GetForecastV2:output_type -> spectre.sample.v1.GetForecastV2Response
	5,  // 12: spectre.sample.v1.WeatherService.GetStatus:output_type -> spectre.sample.v1.GetStatusResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_weather_proto_init() }
func file_weather_proto_init() {
	if File_weather_proto != nil {
		return
	}
	file_weather_proto_msgTypes[1].OneofWrappers = []any{}
	file_weather_proto_msgTypes[3].OneofWrappers = []any{}
	file_weather_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weather_proto_goTypes,
		DependencyIndexes: file_weather_proto_depIdxs,
		MessageInfos:      file_weather_proto_msgTypes,
	}.Build()
	File_weather_proto = out.File
	file_weather_proto_goTypes = nil
	file_weather_proto_depIdxs = nil
}
