// Code generated by spectre-gen json-schema. DO NOT EDIT.
// Source: weather.schema.json, alerts.schema.json

declare module "weather" {
  export interface GetForecastResponse {
    alerts?: import("weather").Alert[];
    "content-type"?: "application/json";
    forecast: import("weather").Forecast;
    labels?: Record<string, string>;
    success?: boolean;
  }

  export interface Forecast {
    days: import("weather").Forecast.Days[];
    location: string;
    next?: import("weather").Forecast;
  }

  export namespace Forecast {
    export interface Days {
      date: string;
      high?: import("weather").Temperature;
      precipitation_percent?: number;
    }
  }

  export interface Temperature {
    degrees?: number;
    unit?: import("weather").Unit;
  }

  export type Tags = string[];

  export type Unit = "celsius" | "fahrenheit";

  export interface Wind {
    speed_kph?: number;
  }

  export type Region = string;

  export interface Alert {
    id: string;
    severity?: import("weather").Severity;
  }

  export type Severity = "minor" | "major";
}
