#!/bin/bash
set -euo pipefail

root="$(dirname "$(readlink -f "$0")")/.."
dest="${root}/dist/devel"
name="$(basename "$0")"
src="./cmd/${name}"
mkdir -p "$dest"

"${root}/bin/go" build -C "${root}/${src}" -ldflags="-s -w -buildid=" -o "$dest/${name}" . && exec "$dest/${name}" "$@"
